/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.sql.*;

import java.sql.ResultSetMetaData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class payment extends javax.swing.JFrame {

    /**
     * Creates new form payment
     */
    private String us;

    public payment() {
        initComponents();
        Connect();
    }
    Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
// Declare jPanel2 globally

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotel", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(room.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String getLoggedInUsername(int userID) {
        // Example of fetching username from a database or session
        String username = "";
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "");
            String query = "SELECT Username FROM user WHERE UserID = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, userID);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                username = rs.getString("Username");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return username;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        txtPayment = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 0, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 255));
        jLabel1.setText("TOTAL AMOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        cmbPaymentMethod.setBackground(new java.awt.Color(204, 0, 255));
        cmbPaymentMethod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbPaymentMethod.setForeground(new java.awt.Color(255, 255, 255));
        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "GCASH", "PAYMAYA", " " }));
        jPanel1.add(cmbPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 141, 32));

        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 284, 41));

        jButton1.setBackground(new java.awt.Color(204, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONFIRM PAYMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 255));
        jLabel2.setText("?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 0, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dgrhhjw-509b3dd4-3050-4db1-8dbd-79a63fac70d2.gif"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempest inn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 255));
        jLabel4.setText("ENTER PAYMENT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 255));
        jLabel5.setText("Choose a payment method");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 190, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dcsc15b-0349fc22-c260-4a76-b5a9-6c86f18ef238 (2).gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 125, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dcsc15b-0349fc22-c260-4a76-b5a9-6c86f18ef238 (2).gif"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String paymentMethod = cmbPaymentMethod.getSelectedItem().toString();
    String paymentAmountText = txtPayment.getText().trim();

    // Validate the payment amount
    if (paymentAmountText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the payment amount.", "Missing Information", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        double paymentAmount = Double.parseDouble(paymentAmountText);

        // Fetch the total amount
        double totalAmount = Double.parseDouble(jLabel2.getText());

        // Fetch the logged-in user's username
        int UserID = Login.UID;  // Use the logged-in user's ID
        String username = getLoggedInUsername(UserID); // Call getLoggedInUsername method to fetch the username

        if (username == null || username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username not found. Unable to proceed.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate payment conditions
        if ("GCash".equalsIgnoreCase(paymentMethod)) {
            if (paymentAmount != totalAmount) {
                JOptionPane.showMessageDialog(this, "GCash payment must be exactly the total amount.", "Payment Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else if (paymentAmount < totalAmount) {
            JOptionPane.showMessageDialog(this, "Insufficient payment amount.", "Payment Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calculate change for overpayment (for Cash or PayMaya)
        double change = paymentAmount - totalAmount;
        if (change > 0) {
            JOptionPane.showMessageDialog(this, "Your change is: " + String.format("%.2f", change), "Change", JOptionPane.INFORMATION_MESSAGE);
        }

        // Store only the total amount in the database
        insertPayment(UserID, paymentMethod, totalAmount);

        // Display a success message
        JOptionPane.showMessageDialog(this, "Payment of " + totalAmount + " via " + paymentMethod + " processed successfully!", "Payment Successful", JOptionPane.INFORMATION_MESSAGE);

        // Pass the username to the finalclient frame
        finalclient obj = new finalclient();
        
        obj.setVisible(true);

        // Dispose of the payment frame
        dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid payment amount. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    private void processPayment() {
        try {
            double paymentAmount = Double.parseDouble(txtPayment.getText());
            JOptionPane.showMessageDialog(this, "Payment of " + paymentAmount + " received via "
                    + cmbPaymentMethod.getSelectedItem(), "Payment Successful", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid payment amount", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void setTotalAmount(double totalAmount) {
        jLabel2.setText(String.format("%.2f", totalAmount)); // Set the total amount label
    }

    private void insertPayment(int userID, String paymentMethod, double paymentAmount) {
    try {
        // Insert payment into the payments table
        String query = "INSERT INTO payments (userID, paymentMethod, paymentAmount) VALUES (?, ?, ?)";
        PreparedStatement pat = con.prepareStatement(query);
        pat.setInt(1, userID);
        pat.setString(2, paymentMethod);
        pat.setDouble(3, paymentAmount);

        // Execute the query
        pat.executeUpdate();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error processing payment: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPayment;
    // End of variables declaration//GEN-END:variables
}
